# Generated by Django 2.1.2 on 2018-10-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=20)),
                ('b_pub_date', models.DateTimeField()),
                ('b_read', models.IntegerField(default=0)),
                ('b_comment', models.IntegerField(default=0)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'book_info',
            },
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=20)),
                ('h_gender', models.BooleanField(default=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('h_content', models.CharField(max_length=100)),
                ('h_book', models.ForeignKey(on_delete=True, to='booktest2.BookInfo')),
            ],
        ),
    ]
